- hosts: ap
  tasks:
    - name: make download local_resources dir
      file: path=./local_resources state=directory mode=777

    - name: make tmp work dir
      file: path=./tmp state=directory mode=777

    - name: download oracle jdk 8
      get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.rpm dest=./local_resources/jdk-8u181-linux-x64.rpm headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no  owner=ec2-user group=ec2-user mode=744

    - name: install jdk 8 from a local file
      become: true
      yum: name=./local_resources/jdk-8u181-linux-x64.rpm state=present

    - name: download wildfly 9.0.2
      get_url: url=http://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.tar.gz dest=./local_resources/

    - name: unarchive wildfly
      become: true
      unarchive: src=./local_resources/wildfly-9.0.2.Final.tar.gz dest=/opt owner=ec2-user group=ec2-user

    - name: observe file
      stat: path=/opt/wildfly
      register: stat_wildfly

    - name: rename wildfly
      become: true
      command: mv /opt/wildfly-9.0.2.Final /opt/wildfly
      when: not stat_wildfly.stat.exists

    - lineinfile:
        dest: /opt/wildfly/bin/init.d/wildfly.conf
        state: present
        insertafter: '# JBOSS_HOME="/opt/wildfly"'
        line: 'JBOSS_HOME="/opt/wildfly'

    - lineinfile:
        dest=/opt/wildfly/bin/init.d/wildfly.conf
        state=present
        insertafter='# JBOSS_USER=wildfly'
        line='JBOSS_USER=ec2-user'

    - lineinfile:
        dest=/opt/wildfly/bin/init.d/wildfly.conf
        state=present
        insertafter='# JBOSS_MODE=standalone'
        line='JBOSS_MODE=standalone'

    - lineinfile:
        dest=/opt/wildfly/bin/init.d/wildfly.conf
        state=present
        insertafter='# JBOSS_CONFIG=standalone.xml'
        line='JBOSS_CONFIG=standalone.xml'

    - lineinfile:
        dest=/opt/wildfly/bin/init.d/wildfly.conf
        state=present
        insertafter='# JBOSS_CONSOLE_LOG="/var/log/wildfly/console.log"'
        line='JBOSS_CONSOLE_LOG=/var/log/wildfly/console.log'

#    - name: make download local_resources dir
#      become: true
#      file: path=/etc/init.d/wildfly state=directory

#    - name: make download local_resources dir
#      become: true
#      file: path=/etc/default/wildfly state=directory

    - name: register init.d
      become: true
      copy:
        src: /opt/wildfly/bin/init.d/wildfly-init-redhat.sh
        dest: /etc/init.d/wildfly

    - name: change mode
      become: true
      command: "chmod +x /etc/init.d/wildfly"

    - name: set service on boot(deprecated -- you'd better use sys-rc-conf --add wildfly)
      become:true
      command: "chkconfig --add wildfly"

#    - name: copy wildfly config
#      become: true
#      copy:
#        src: /opt/wildfly/bin/init.d/wildfly.conf
#        dest: /etc/default/widlfly

#    - name: setup wildfly service
#      become: true
#      command: /opt/wildfly/bin/init.d/wildfly-init-redhat.sh

    - name: start service
      become: true
      service: name=wildfly state=started

