- hosts: localhost
  tasks:
    - name: make download soft dir
      file: path=./local_resources state=directory mode=777

    - name: download oracle jdk 8
      get_url: url=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.rpm dest=./local_resources/jdk-8u181-linux-x64.rpm headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no  owner=ec2-user group=ec2-user mode=744

    - name: install jdk 8 from a local file
      become: true
      yum: name=./local_resources/jdk-8u181-linux-x64.rpm state=present

    - name: download wildfly 9.0.2
      get_url: url=http://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.tar.gz dest=./local_resources/ owner=ec2-user group=ec2-user

