

- hosts: ap
  become: true
  vars:
    work_path: "{{ ansible_env.PWD }}/documentation"

  tasks:
    - name: install netcat(疎通確認に利用)
      yum: name=nc

    - name: install epel
      #become: true
      #command: "yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"     
      yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm" state=latest

    - name: install node.js
      become: true
      command: "yum install -y nodejs npm --enablerepo=epel"
      
    - name: install gcc gcc-c++
    # npmで利用する場合があるのでgccを入れる
      become: true
      command: "yum install -y gcc gcc-c++"
      
    - name: install gitbook
      become: true
      command: "npm install -g gitbook-cli"

    - name: gitbook help
      # become: true
      command: "gitbook help"
      
    # test（別ファイルに移した方がよい）
      
    - name: download sample document
      # become: true
      command: "git clone https://github.com/GitbookIO/documentation.git"
      when: work_path is not exists
 
    - name: gitbook build
    # cloneしたリポジトリを指定
      become: true
      command: "gitbook build {{ work_path }}"
     
    - name: start gitbook serve
    # cloneしたリポジトリを指定
      become: true
      async: 5
      poll: 0      
      command: "gitbook serve {{ work_path }} &"
      
    - name: wait until stated gitbook serve
    # サーバの起動時間を考慮しテストを実行
      # become: true
      command: "sleep 5"
      
    - name: test http response
      # become: true
      #command: "curl http://localhost:4000"
      command: nc {{ item.host }} {{ item.port }}
      with_items:
        - { host: localhost, port: 4000 }      

    # 上手くkillが実行できないし、ansibleが勝手にプロセスをkillしてくれるので実行しない

    #- name: get pid of gitbook and kill
      # become: true
    #  shell: "pid_gitbook=`pgrep -f 'gitbook serve'`; kill $pid_gitbook"
    
    - name: install wget(calibreで利用)
      yum: name=wget state=latest
      
    - name: install wget(calibreで利用)
      yum: name=qt-creator state=latest

    - name: install calibre(pdf, epub出力のためにgitbookが利用する)
      shell: "sudo wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin"

