
sudo tee /etc/yum.repos.d/mongodb-org-4.0.repo << EOS
[mongodb-org-4.0]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/7Server/mongodb-org/4.0/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-4.0.asc

EOS

sudo yum install -y mongodb-org

sudo systemctl start mongod




# practice

# ログイン
mongo

use study

db.stats()
db.user.insert({name:'mr.a',age:10,gender:'m',hobbies:['programing']});
db.user.insert({name:'ms.c', age:30, gender:'f', hobbies:['programming', 'vi']});
db.user.find();

